# Generated by Django 4.1.7 on 2023-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_quiz', '0002_user_remove_profile_follower_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
